title: GameDriver Pro
logo: /assets/img/logo.png
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

i18n_cn: 0
i18n_en: 1

author:
  name: XUZHUOXI
  home_page_url: https://www.xuzhuoxi.com/

unity:
  package_url: https://assetstore.unity.com/packages/slug/234202
  publisher_url: https://assetstore.unity.com/publishers/74539

home:
  url: https://www.xuzhuoxi.com/GameDriver-Docs

github:
  issues_url: https://github.com/xuzhuoxi/GameDriver-Docs/issues
  issues_new_url: https://github.com/xuzhuoxi/GameDriver-Docs/issues/new

downloads:
  manaual_cn_pdf: 'https://www.xuzhuoxi.com/GameDriver-Docs/downloads/GameDriver Pro Manaual_cn.pdf'
  manaual_en_pdf: 'https://www.xuzhuoxi.com/GameDriver-Docs/downloads/GameDriver Pro Manaual_en.pdf' 
