title: GameDriver Pro
logo: /assets/img/logo.png
description: GameDriver Pro is a game framework for Unity engine.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

unity:
  package_url: https://assetstore.unity.com/packages/slug/234202
  publisher_url: https://assetstore.unity.com/publishers/74539
github:
  home_url: https://www.xuzhuoxi.com/GameDriver-Docs
  manual_cn_url: https://www.xuzhuoxi.com/GameDriver-Docs/Page-Manual_cn.html
  manual_en_url: https://www.xuzhuoxi.com/GameDriver-Docs/Page-Manual_en.html
  issues_url: https://github.com/xuzhuoxi/GameDriver-Docs/issues
  issues_new_url: https://github.com/xuzhuoxi/GameDriver-Docs/issues/new
  
  downloads:
    manaual_cn_pdf: 'https://www.xuzhuoxi.com/GameDriver-Docs/downloads/GameDriver Pro Manaual_cn.pdf'
    manaual_en_pdf: 'https://www.xuzhuoxi.com/GameDriver-Docs/downloads/GameDriver Pro Manaual_en.pdf'
show_navigation: false