title: GameDriver Pro
logo: /assets/img/logo.png
description: GameDriver Pro is a game framework for Unity engine.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

show_navigation: false

author:
  name: XUZHUOXI
  home_page_url: https://www.xuzhuoxi.com/

unity:
  package_url: https://assetstore.unity.com/packages/slug/234202
  publisher_url: https://assetstore.unity.com/publishers/74539

docs:
  url: https://www.xuzhuoxi.com/GameDriver-Docs
  readme_url: https://www.xuzhuoxi.com/GameDriver-Docs/Page-README.html
  changelog_url: https://www.xuzhuoxi.com/GameDriver-Docs/Page-CHANGELOG.html
  manual_cn_url: https://www.xuzhuoxi.com/GameDriver-Docs/Page-Manual_cn.html
  manual_en_url: https://www.xuzhuoxi.com/GameDriver-Docs/Page-Manual_en.html
  FAQs_url: https://www.xuzhuoxi.com/GameDriver-Docs/Page-FAQs.html
  third_party_notices_url: https://www.xuzhuoxi.com/GameDriver-Docs/Page-ThirdPartyNotices.html

github:
  issues_url: https://github.com/xuzhuoxi/GameDriver-Docs/issues
  issues_new_url: https://github.com/xuzhuoxi/GameDriver-Docs/issues/new

downloads:
  manaual_cn_pdf: 'https://www.xuzhuoxi.com/GameDriver-Docs/downloads/GameDriver Pro Manaual_cn.pdf'
  manaual_en_pdf: 'https://www.xuzhuoxi.com/GameDriver-Docs/downloads/GameDriver Pro Manaual_en.pdf' 
